DROP TABLE IF EXISTS `USERS` CASCADE;
DROP TABLE IF EXISTS `RECIPE` CASCADE;
DROP TABLE IF EXISTS `USERS_SAVED_RECIPES` CASCADE;


CREATE TABLE `USERS` (
    `EMAIL` VARCHAR(255) PRIMARY KEY,
    `FIRSTNAME` VARCHAR(255),
    `SURNAME` VARCHAR(255),
    `PASSWORD` VARCHAR(255)
);

CREATE TABLE `RECIPE` (
    `RECIPE_ID` VARCHAR(255) PRIMARY KEY
);

CREATE TABLE `USERS_SAVED_RECIPES` (
    `USERS_EMAIL` VARCHAR(255),
    `SAVED_RECIPES_RECIPE_ID` VARCHAR(255),
    PRIMARY KEY (`SAVED_RECIPES_RECIPE_ID`, `USERS_EMAIL`),
    FOREIGN KEY (`SAVED_RECIPES_RECIPE_ID`) REFERENCES `RECIPE`(`RECIPE_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`USERS_EMAIL`) REFERENCES `Users`(`EMAIL`) ON DELETE CASCADE
);