const TestRecipe = [{ "idMeal": "52952",
        "strMeal": "Beef Lo Mein",
        "strDrinkAlternate": null,
        "strCategory": "Beef",
        "strArea": "Chinese",
        "strInstructions": "STEP 1 - MARINATING THE BEEF\r\nIn a bowl, add the beef, salt, 1 pinch white pepper, 1 Teaspoon sesame seed oil, 1/2 egg, corn starch,1 Tablespoon of oil and mix together.\r\nSTEP 2 - BOILING THE THE NOODLES\r\nIn a 6 qt pot add your noodles to boiling water until the noodles are submerged and boil on high heat for 10 seconds. After your noodles is done boiling strain and cool with cold water.\r\nSTEP 3 - STIR FRY\r\nAdd 2 Tablespoons of oil, beef and cook on high heat untill beef is medium cooked.\r\nSet the cooked beef aside\r\nIn a wok add 2 Tablespoon of oil, onions, minced garlic, minced ginger, bean sprouts, mushrooms, peapods and 1.5 cups of water or until the vegetables are submerged in water.\r\nAdd the noodles to wok\r\nTo make the sauce, add oyster sauce, 1 pinch white pepper, 1 teaspoon sesame seed oil, sugar, and 1 Teaspoon of soy sauce.\r\nNext add the beef to wok and stir-fry",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/1529444830.jpg",
        "strTags": null,
        "strYoutube": "https://www.youtube.com/watch?v=ZT9LSsNXXe0",
        "strIngredient1": "Beef",
        "strIngredient2": "Salt",
        "strIngredient3": "Pepper",
        "strIngredient4": "Sesame Seed Oil",
        "strIngredient5": "Egg",
        "strIngredient6": "Starch",
        "strIngredient7": "Oil",
        "strIngredient8": "Noodles",
        "strIngredient9": "Onion",
        "strIngredient10": "Minced Garlic",
        "strIngredient11": "Ginger",
        "strIngredient12": "Bean Sprouts",
        "strIngredient13": "Mushrooms",
        "strIngredient14": "Water",
        "strIngredient15": "Oyster Sauce",
        "strIngredient16": "Sugar",
        "strIngredient17": "Soy Sauce",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1/2 lb",
        "strMeasure2": "pinch",
        "strMeasure3": "pinch",
        "strMeasure4": "2 tsp",
        "strMeasure5": "1/2 ",
        "strMeasure6": "3 tbs",
        "strMeasure7": "5 tbs",
        "strMeasure8": "1/4 lb",
        "strMeasure9": "1/2 cup ",
        "strMeasure10": "1 tsp ",
        "strMeasure11": "1 tsp ",
        "strMeasure12": "1 cup ",
        "strMeasure13": "1 cup ",
        "strMeasure14": "1 cup ",
        "strMeasure15": "1 tbs",
        "strMeasure16": "1 tsp ",
        "strMeasure17": "1 tsp ",
        "strMeasure18": "",
        "strMeasure19": "",
        "strMeasure20": "",
        "strSource": "https://sueandgambo.com/pages/beef-lo-mein",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }, 
    {
        "idMeal": "53080",
        "strMeal": "Blini Pancakes",
        "strDrinkAlternate": null,
        "strCategory": "Side",
        "strArea": "Russian",
        "strInstructions": "In a large bowl, whisk together 1/2 cup buckwheat flour, 2/3 cup all-purpose flour, 1/2 teaspoon salt, and 1 teaspoon yeast.\r\n\r\nMake a well in the center and pour in 1 cup warm milk, whisking until the batter is smooth.\r\n\r\nCover the bowl and let the batter rise until doubled, about 1 hour.\r\n\r\nEnrich and Rest the Batter\r\nStir 2 tablespoons melted butter and 1 egg yolk into the batter.\r\n\r\nIn a separate bowl, whisk 1 egg white until stiff, but not dry.\r\n\r\nFold the whisked egg white into the batter.\r\n\r\nCover the bowl and let the batter stand 20 minutes.\r\n\r\nPan-Fry the Blini\r\nHeat butter in a large nonstick skillet over medium heat.\r\n\r\nDrop quarter-sized dollops of batter into the pan, being careful not to overcrowd the pan. Cook for about 1 minute or until bubbles form.\r\n\r\nTurn and cook for about 30 additional seconds.\r\n\r\nRemove the finished blini onto a plate and cover them with a clean kitchen towel to keep warm. Add more butter to the pan and repeat the frying process with the remaining batter.",
        "strMealThumb": "https://www.themealdb.com/images/media/meals/0206h11699013358.jpg",
        "strTags": "pancake",
        "strYoutube": "https://www.youtube.com/watch?v=GsB8ZI5vREA",
        "strIngredient1": "Buckwheat",
        "strIngredient2": "Flour",
        "strIngredient3": "Salt",
        "strIngredient4": "Yeast",
        "strIngredient5": "Milk",
        "strIngredient6": "Butter",
        "strIngredient7": "Egg",
        "strIngredient8": "",
        "strIngredient9": "",
        "strIngredient10": "",
        "strIngredient11": "",
        "strIngredient12": "",
        "strIngredient13": "",
        "strIngredient14": "",
        "strIngredient15": "",
        "strIngredient16": "",
        "strIngredient17": "",
        "strIngredient18": "",
        "strIngredient19": "",
        "strIngredient20": "",
        "strMeasure1": "1/2 cup ",
        "strMeasure2": "2/3 Cup",
        "strMeasure3": "1/2 tsp",
        "strMeasure4": "1 tsp ",
        "strMeasure5": "1 cup ",
        "strMeasure6": "2 tbs",
        "strMeasure7": "1 Seperated",
        "strMeasure8": " ",
        "strMeasure9": " ",
        "strMeasure10": " ",
        "strMeasure11": " ",
        "strMeasure12": " ",
        "strMeasure13": " ",
        "strMeasure14": " ",
        "strMeasure15": " ",
        "strMeasure16": " ",
        "strMeasure17": " ",
        "strMeasure18": " ",
        "strMeasure19": " ",
        "strMeasure20": " ",
        "strSource": "https://www.thespruceeats.com/russian-blini-recipe-buckwheat-pancakes-1136797",
        "strImageSource": null,
        "strCreativeCommonsConfirmed": null,
        "dateModified": null
    }]

export default TestRecipe